rhel7_job:
  tags:
  - rhel7
  before_script:
  - cp configure/RELEASE configure/RELEASE.vcs
  - git cat-file -p HEAD:configure/RELEASE > configure/RELEASE.vcs
  - rm configure/RELEASE
  - sed -e 's,^ *EPICS_BASE *=.*$,EPICS_BASE='$EPICS_BASE',' -e 's,^ *SUPPORT *=.*$,SUPPORT=/dls_sw/prod/'$(echo $EPICS_BASE | cut -d/ -f4)'/support,' -e 's,^ *WORK *=.*$,#WORK=commented out to prevent prod modules depending on work modules,' configure/RELEASE.vcs > configure/RELEASE
  - echo "EPICS_BASE=${EPICS_BASE}" >> configure/RELEASE.${EPICS_HOST_ARCH}
  - echo "SUPPORT=/dls_sw/prod/$(echo $EPICS_BASE | cut -d/ -f4)/support" >> configure/RELEASE.${EPICS_HOST_ARCH}
  - cat configure/RELEASE.${EPICS_HOST_ARCH}  
  - cp configure/RELEASE.${EPICS_HOST_ARCH} configure/RELEASE.${EPICS_HOST_ARCH}.Common

  script:
  - make
